### PR TITLE
Html text support

### PR DESCRIPTION
**Pull request by andreipro**
Add html text support for the message text in the Confirm dialog (on Android).

### CODE REVIEW

**Comment by aritchie** [comment]
I'm afraid I can't merge this until iOS at the least is filled otherwise I'll be stuck explaining to every user the one sided implementation of this.

**Comment by andreipro** [comment]
@aritchie Hey, thanks for reply. I made the implementation on iOS and now it supports both Alert and Confirm dialogs. There are still some improvements to be made, so it's not quite ready for merge. I encounter a problem with the UIAlertController regarding it's content width. Apparently we can't get it's real width and right now I'm calculating it based on the model device (as far as I tested, some values from AlertUtils class are wrong and needs more research on it). You can check the last commit I made, and if you have any feedback please let me know. Thanks.

**Comment by aritchie** [comment]
Thanks for the great PR.  I'm going to incorporate this into v7, but across all of the dialogs.  The only thing I see as a potential issue is the way iOS' default views get changed.  The dialog view should not be touched unless HTML text is actually being used.  I'll adjust that as it isn't a big deal.

**Comment by andreipro** [comment]
@aritchie Hey, yes I removed that flag for html text from android also. I will re-add it and use the custom views only when that flag is true. If I have time I'll make the modifications tomorrow, and will let you know. When are you planning to release v7, do you have any eta? Thanks

**Comment by andreipro** [comment]
@aritchie I made another commit

**Comment by aritchie** [comment]
I wanted you to know that this is slated for 7.1.  I haven't forgotten about it.  Just too many deliverables in the pipeline right now

**Pull request closed without merging**
