### PR TITLE
add 'setmessage' method when building actionsheet

### PR DESCRIPTION
**Pull request by shmoogems**
#425

### CODE REVIEW

**Comment by shmoogems** [comment]
#425

**Comment by aritchie** [comment]
Unfortunately, I have to decline this PR.  If you add message, it will remove the actual buttons from the actionsheet.  You'll notice there is a custom view section commented out.  This was a starting point that I never finished.

**Comment by shmoogems** [comment]
Thanks - I did test it locally and it seemed fine. Can you advise on a time that you are you looking at implementing this? Or can you advise on a path that we may take to implement it ourselves?

**Comment by aritchie** [comment]
This is OSS.  You can take your own copy at anytime.  

I'm have no plans on implementing this at the moment.

**Pull request closed without merging**
