### PR TITLE
[iOS] Increased left margin of toast text

### LINKED ISSUE #596: [Ios] Toast message has no left spacing
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of ACR UserDialogs Library

- 7.0.4

## Expected Behaviour

Gap between left edge of toast, and left edge of toast message

## Actual Behavior

The left alignment of the Toast message (spacing between the left edge of the toast, and the left edge of the message) is currently 0. This does not look right, and should be increased (e.g. 10).

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

### PR DESCRIPTION
**Pull request by andnes-cap**
Fixes #596 
I increased the left margin to 10, as suggested.

### CODE REVIEW

**Comment by aritchie** [comment]
Thanks for the pr

**Comment by FinHorsley** [comment]
When will an update be available on Nuget that includes this change?

**Comment by FinHorsley** [comment]
When will this change be available via Nuget?

**Comment by aritchie** [comment]
@FinHorsley Did you notice I deleted your last message that asked this?  This is also the second time you've been a pain.

1. Do you pay for this library? - No
2. Have you contributed to this library? - No
3. Do I owe you or anyone using this a timeline - no
4. Am I going to issue a build for one minor fix - no 
5. Did you file this issue? - yes
6. Did you commit this fix? - no 

If you are going to repeatedly act entitled, please go elsewhere.

**Comment by FinHorsley** [comment]
This wasn't meant to be an entitled question so apologies for that, I was just interested as to when it might be available. This is a great pr, and will allow us to clean up our code a fair bit

I didn't know whether the upload to Nuget was automated as part of a build pipeline once the PR was merged, or whether it is a more manual process

**Pull request merged**
