### PR TITLE
Added icons to actionsheet

### PR DESCRIPTION
**Pull request by martijn00**
Fix for https://github.com/aritchie/userdialogs/issues/59

### CODE REVIEW

**Comment by aritchie** [comment]
awesome.  thanks very much.  I'll get this integrated and out the door tonight

**Comment by martijn00** [comment]
I just tested the updated packages, but it seems you didn't include this code in it?

**Comment by aritchie** [comment]
I left platform as "iPhone Simulator" :P  Brain moment.  Anyhow, 4.1.3 will be on nuget shortly.  I'll stick a build script on this in the near future.

**Comment by martijn00** [comment]
Thanks, this seems to work now. I will do some further testing to ensure everything works correctly. One thing our designer noticed is that the width, heights and sizes are a bit off on Android and UWP. I'll make a PR to fix this.

**Comment by aritchie** [comment]
UWP is all off right now.  I'm hiding behind a beta tag on it until I actively start using it.  I imagine once mvx4 goes stable, there will be a lot more requests around it.

**Pull request merged**
