### PR TITLE
fix left and right padding on TextView in Prompt

### LINKED ISSUE #389: [Android] Prompt textbox needs padding
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
Android 6.0.1 / 8.0

## Version of ACR UserDialogs Library
6.4.1

## Expected Behaviour
EditText should have default AlertDialogs Padding Left and Right

## Actual Behavior
Using a Prompt the EditText seems to have no padding on the left side in the displayed AlertDialog (Screenshot below).

I believe a possible solution would be to set the paddings manually while setting calling the `SetView()` Method on the dialog object [PromptBuilder.cs](https://github.com/aritchie/userdialogs/blob/master/src/Acr.UserDialogs.Android/Builders/PromptBuilder.cs#L79). ([Stackoverflow Padding on AlertDialog](https://stackoverflow.com/questions/33074313/getting-default-padding-for-alertdialog))

What I am unsure of is how to handle different Android Versions (also Themes?) . Maybe I am also missing something and this actually works, if so, would be nice to point me in the right direction.

screen

### PR DESCRIPTION
**Pull request by veryhumble**
A possible implementation to close #389

### CODE REVIEW

**Comment by mattrichnz** [comment]
This is such a small change, but can it please be considered?
Right now, the TextView Android doesn't look good at all, almost unfinished.

Just a small amount of padding will make all the difference here. 👍

**Comment by DevEddy** [comment]
Yes, agree mattrichnz. It would be awesome with padding.

// EDDY

**Comment by aritchie** [comment]
You guys can +1 this all you want (which is against my code of conduct btw).  It only serves to irritate me so that I close this out entirely.  The fact is that I'm the guy that has to test this on all of the android versions which sucks and I think the prompt is a horrid user experience in any context you use it presently.  

I will get to this in a near future release.  If the +1's continue, forget it.

**Comment by mattrichnz** [comment]
@aritchie Appreciate your comments. I understand your frustration, but I would be willing to work on this PR or another and test on the entire range of Android devices in our test lab. We have a high-volume app which uses ACRUserDialogs, so it is in our interest too to help you maintain a high level of QA and improve this great library.

Please reach out to me via DM if you are interested and we can work together on this.

**Pull request closed without merging**
