### PR TITLE
Feature/number picker

### PR DESCRIPTION
**Pull request by juanagu**
* Add Number picker for iOS and Android.
* Add in Sample [Standard "Number Picker"]
* TODO MacOS, Uwp

### CODE REVIEW

**Comment by juanagu** [comment]
@aritchie Do you can review this pull request?

**Comment by aritchie** [comment]
@juanagu be patient - I will get to it when I have time.  It likely won't be for a couple of weeks.

**Comment by juanagu** [comment]
@aritchie Ok! Thanks!

**Comment by aritchie** [comment]
First off, thanks for the PR.

However, I believe this functionality (drop down selection) is better served elsewhere and not in a dialog this way.  This library already is bloated by features so I'm not keen on adding more to it especially when I believe it can be done better using other mechanisms (ie. Viewmodels with standard views).

Please add some screenshots and further explanation for your use-cases.

**Comment by juanagu** [comment]
I using Xamarin Forms. I think that Number Picker is very util for "Quick insert of a number" value, e.g to insert values in a list to pending routes.
I using the number picker for add product quantity in list page. For iOS the current implementation to picker is very good, but for Android if you have a long list to possible numbers to select the component has a bad UX, for this reason the native Android.Number picker implementation has a better UX.

**Number picker samples:**
_iOS:_
iOS sample

_Android:_
Android sample

**Comment by aritchie** [comment]
I'm sorry.  While I appreciate the PR, I've decided to pass on this.  I feel things like this are better served elsewhere.  I'm attempting to cut back on some of the bloat in the library at this point anyhow.

**Pull request closed without merging**
