### PR TITLE
ability to init from a custom Application, not only the first Activity

### PR DESCRIPTION
**Pull request by benoitjadinon**
hey man, so, I had an issue with Acr.UserDialogs, I wanted to init it from a custom Android Application (before any Activity then) and also register the .Instance to DI at the same place (still before any Activity)
but the Init() needed an activity and the .Instance needed the Init() to be executed.
so I added a way to init from Application, what do you think ?
(sorry for the line reordering, XS did it automagically)

### CODE REVIEW

**Comment by aritchie** [comment]
Hey Benoit
I appreciate the PR, but I have a much easier way to solve this for you.  I'll post it with 4.0.3 in the next couple of hours

**Comment by aritchie** [comment]
Actua

**Comment by aritchie** [comment]
Actually, I looked closer at this and I was curious.  Why do you want to init from a custom application?  Passing in the first activity should not break your use-case.  User dialogs does need the first activity due to most android apps being a single activity these days (so the lifecycle callbacks never get triggered).  

You could register the lifecycle callbacks yourself in your custom app and then create the instance of userdialogs yourself.  I just don't want to overcomplicate the init process without a very strong reason.

I did readd the custom activity factory function to allow for external management of the top activity.  Not sure if this helps you out or not.

Let me know.

**Comment by benoitjadinon** [comment]
Personal opinion probably, I like my activities (aka viewcontrollers as I see them) to do as little logic and setup as possible, so I can swap one for the other as the main activity (as my clients change their minds at the end of each project hehe), and not having to care about wether that one Activity was doing more than showing some view.

I think the Application is a better place to setup dependencies and other stuff.

In my last project, DI setup was done outside as well, then I had to wait for the first activity to call the Init(), and then only RegisterInstance<>(UserDialog.Instance), so it was lying there, far from the other registers, in the middle of what I still think is a view.

See what I mean ?

And yes, I ended up creating the callback and Instance myself, it's working, feels a bit hacky, where it could be a clean overload on Init inside the lib. 

If there is no implication for CurrentTopActivity being null at application create time, I don't think so.

**Comment by aritchie** [comment]
I have added this to the new support package and current set of init methods as of 4.0.4

**Comment by benoitjadinon** [comment]
awesome ! thanks :+1:

**Pull request closed without merging**
